### PR TITLE
v3.0 - Swift Rewrite 

### PR DESCRIPTION
**Pull request by ryang1428**

### CODE REVIEW

**Comment by ryang1428** [comment]
Finally passing travis ! 🙏 🎉  This is ready to go in

**Review by codecaffeine — CHANGES_REQUESTED** [review]
I’m seeing some of the following issues going through the example:
1. Custom Style: No corner radius is displaying
2. Textfield Validation doesn’t re-enable the done button after it gets an initial error
3. The passive alert have weird gray bars underneath

**Comment by ryang1428** [comment]
Hm interesting I wonder if they are iOS 11 issues, or things that weren't working correct before. I'll take a look

**Comment by ryang1428** [comment]
err I meant swift 4.2 issues

**Comment by ryang1428** [comment]
@codecaffeine I fixed up those issues. Regarding #2, I just removed disabling that button... we don't have the functionality built into handle re-enabling that on the fly. I think that was just some bad code in the example.

**Review by codecaffeine — APPROVED** [review]

**Review by Lloyd1nSpace-zz — APPROVED** [review]

**Pull request merged**
